# מילון התרגומים המרכזי
TRANS = {
    "HE": {
        "dir": "rtl", "align": "right",
        "nav_title": "תפריט ראשי",
        "nav_dashboard": "דשבורד ולידים", "nav_schedule": "📅 יומן", "nav_settings": "הגדרות בוט", "nav_pros": "אנשי מקצוע", "nav_add_pro": "➕ הוסף איש מקצוע",
        "welcome_message": "ברוך הבא למרכז השליטה", "admin_password_label": "סיסמת מנהל", "admin_password_placeholder": "הכנס סיסמה כאן...",
        "remember_me": "זכור אותי (Keep me logged in)", "login_button": "כניסה למערכת", "wrong_password": "❌ סיסמה שגויה. נסה שוב.",
        "title_dashboard": "📊 מרכז שליטה",
        "metric_total": "סה\"כ לידים", "metric_new": "לידים חדשים", "metric_pros": "אנשי מקצוע",
        "table_title": "📋 ניהול לידים",
        "col_date": "תאריך", "col_details": "פרטים", "col_status": "סטטוס", "col_client": "לקוח", "col_pro": "טופל ע\"י",
        "chat_history": "💬 היסטוריית שיחה", "no_chat": "אין היסטוריה זמינה.",
        "action_update": "ניהול ליד נבחר", "btn_update": "עדכן סטטוס", "success_update": "עודכן בהצלחה!",
        "settings_title": "🧠 הגדרות בוט", "select_pro": "בחר פרופיל לעריכה", "edit_title": "עריכת פרופיל", "save_btn": "שמור שינויים", "success_save": "השינויים נשמרו בהצלחה!",
        "pros_title": "👷 ניהול צוות", "phone": "טלפון", "active": "פעיל?", "areas": "אזורי שירות", "keywords": "מילות מפתח", "prompt_title": "הנחיות מערכת", "prompt_desc": "הגדרות התנהגות הבוט",
        "rating": "דירוג", "role_user": "לקוח", "role_bot": "בוט",
        "status_active": "פעיל", "status_inactive": "לא פעיל", "no_leads_found": "לא נמצאו לידים.",
        "status": "סטטוס", "new": "חדש", "contacted": "טופל", "closed": "נסגר", "cancelled": "בוטל", "booked": "נקבע תור",
        "add_pro_title": "✨ הוספת איש מקצוע חדש", "new_name": "שם העסק", "new_phone": "מספר טלפון (972...)",
        "new_type": "תחום עיסוק", "type_plumber": "אינסטלטור", "type_electrician": "חשמלאי",
        "new_areas": "ערים (מופרד פסיקים)", "new_prices": "מחירון בסיס (טקסט חופשי)",
        "btn_create": "צור פרופיל ויומן", "success_create": "הפרופיל נוצר בהצלחה! יומן הוגדר לשבוע הקרוב.",
        "title_schedule": "📅 ניהול יומן",
        "sch_select_pro": "בחר יומן לצפייה", "sch_date": "תאריך", "sch_time": "שעה", "sch_taken": "תפוס?",
        "sch_save": "שמור שינויים ביומן", "sch_success": "היומן עודכן בהצלחה!", "sch_filter_date": "סנן לפי תאריך (אופציונלי)",
        "sch_config_title": "⚙️ הגדרות יצירת יומן", "sch_start_date": "תאריך התחלה", "sch_end_date": "תאריך סיום",
        "sch_start_hour": "שעת התחלה (0-23)", "sch_end_hour": "שעת סיום (0-23)", "sch_duration": "משך תור (דקות)",
        "sch_workdays": "ימי עבודה", "sch_gen_btn": "צור סלוטים", "sch_clear_btn": "נקה סלוטים עתידיים",
        "sch_msg_generated": "סלוטים נוצרו בהצלחה!", "sch_msg_cleared": "היומן נוקה בהצלחה!",
        "day_0": "ראשון", "day_1": "שני", "day_2": "שלישי", "day_3": "רביעי", "day_4": "חמישי", "day_5": "שישי", "day_6": "שבת",
        "unknown_pro": "לא ידוע", "select_lead": "בחר ליד", "select_status": "בחר סטטוס",
        "no_slots": "אין תורים בתאריך זה.", "slot_help": "סמן אם התור תפוס/חסום",
        "msg_changes": "שינויים", "no_changes": "לא בוצעו שינויים.",
        "schedule_empty": "היומן ריק. כנס ל'הגדרות בוט' כדי ליצור יומן חדש.",
        "disconnect": "🔒 התנתק"
    },
"EN": {
        "dir": "ltr", "align": "left",
        "nav_title": "Main Menu",
        "nav_dashboard": "Dashboard", "nav_schedule": "📅 Schedule", "nav_add_pro": "➕ Add Pro", "nav_settings": "Settings", "nav_pros": "Professionals",
        "welcome_message": "Welcome to the Control Center", "admin_password_label": "Admin Password", "admin_password_placeholder": "Enter password here...",
        "remember_me": "Remember me (Keep me logged in)", "login_button": "Login", "wrong_password": "❌ Wrong password. Try again.",
        "title_dashboard": "📊 Control Center", "title_schedule": "📅 Schedule Manager",
        "metric_total": "Total Leads", "metric_new": "New Leads", "metric_pros": "Active Pros",
        "table_title": "📋 Leads Management",
        "col_date": "Date", "col_details": "Details", "col_status": "Status", "col_client": "Client", "col_pro": "Assignee",
        "chat_history": "💬 Chat History", "no_chat": "No history available.", "action_update": "Manage Selected Lead", "btn_update": "Update Status", "success_update": "Updated successfully!",
        "settings_title": "🧠 Bot Settings", "select_pro": "Select Profile", "edit_title": "Edit Profile", "save_btn": "Save Changes", "success_save": "Changes saved successfully!",
        "pros_title": "👷 Team List", "phone": "Phone", "active": "Active?", "areas": "Service Areas", "keywords": "Keywords", "prompt_title": "System Prompt", "prompt_desc": "Behavior settings", "rating": "Rating", "role_user": "Client", "role_bot": "Bot",
        "status_active": "Active", "status_inactive": "Inactive", "no_leads_found": "No leads found.",
        "status": "Status", "new": "New", "contacted": "Contacted", "closed": "Closed", "cancelled": "Cancelled", "booked": "Booked",
        "add_pro_title": "✨ Add New Professional", "new_name": "Business Name", "new_phone": "Phone Number",
        "new_type": "Profession", "type_plumber": "Plumber", "type_electrician": "Electrician",
        "new_areas": "Cities", "new_prices": "Pricing", "btn_create": "Create Profile", "success_create": "Created successfully!",
        "title_schedule": "📅 Schedule Manager",
        "sch_select_pro": "Select Calendar", "sch_date": "Date", "sch_time": "Time", "sch_taken": "Taken?",
        "sch_save": "Save Schedule Changes", "sch_success": "Schedule updated!", "sch_filter_date": "Filter by Date",
        "sch_config_title": "⚙️ Schedule Generator", "sch_start_date": "Start Date", "sch_end_date": "End Date",
        "sch_start_hour": "Start Hour (0-23)", "sch_end_hour": "End Hour (0-23)", "sch_duration": "Slot Duration (minutes)",
        "sch_workdays": "Work Days", "sch_gen_btn": "Generate Slots", "sch_clear_btn": "Clear Future Slots",
        "sch_msg_generated": "Slots generated successfully!", "sch_msg_cleared": "Schedule cleared successfully!",
        "day_0": "Sunday", "day_1": "Monday", "day_2": "Tuesday", "day_3": "Wednesday", "day_4": "Thursday", "day_5": "Friday", "day_6": "Saturday",
        "unknown_pro": "Unknown", "select_lead": "Select Lead", "select_status": "Select Status",
        "no_slots": "No slots on this date.", "slot_help": "Check if slot is taken/blocked",
        "msg_changes": "changes", "no_changes": "No changes made.",
        "schedule_empty": "Schedule is empty. Go to 'Bot Settings' to create a new schedule.",
        "disconnect": "🔒 Logout"
    }
}