# מילון התרגומים המרכזי
TRANS = {
    "HE": {
        "dir": "rtl", "align": "right",
        "nav_title": "תפריט ראשי",
        "nav_dashboard": "📊 דשבורד ולידים", "nav_schedule": "📅 יומן עבודה", "nav_settings": "⚙️ הגדרות מערכת", "nav_pros": "👷 אנשי מקצוע", "nav_add_pro": "➕ הוספת עובד",
        "welcome_message": "ברוך הבא למרכז השליטה", "admin_password_label": "סיסמת מנהל", "admin_password_placeholder": "הכנס סיסמה כאן...",
        "remember_me": "זכור אותי (Keep me logged in)", "login_button": "כניסה למערכת", "wrong_password": "❌ סיסמה שגויה. נסה שוב.",
        "title_dashboard": "מרכז שליטה וניהול",
        "metric_total": "סה\"כ לידים", "metric_new": "לידים ממתינים", "metric_pros": "צוות פעיל",
        "table_title": "ניהול לידים ומשימות",
        "col_date": "תאריך פנייה", "col_details": "פרטי בקשה", "col_status": "סטטוס טיפול", "col_client": "פרטי לקוח", "col_pro": "משויך ל...",
        "chat_history": "היסטוריית התכתבות", "no_chat": "אין היסטוריה זמינה לשיחה זו.",
        "action_update": "פעולות על ליד נבחר", "btn_update": "עדכן סטטוס", "success_update": "הסטטוס עודכן בהצלחה!",
        "settings_title": "הגדרות מערכת ובוט AI", "select_pro": "בחר פרופיל לעריכה", "edit_title": "עריכת פרופיל עסק", "save_btn": "שמור שינויים", "success_save": "השינויים נשמרו בהצלחה!",
        "pros_title": "צוות אנשי המקצוע", "phone": "טלפון", "active": "פעיל במערכת?", "areas": "אזורי שירות (ערים)", "keywords": "מילות מפתח לזיהוי", "prompt_title": "הנחיות אישיות לבוט (System Prompt)", "prompt_desc": "כאן מגדירים את האישיות והידע של הבוט עבור איש המקצוע",
        "rating": "דירוג לקוחות", "role_user": "לקוח", "role_bot": "נציג דיגיטלי",
        "status_active": "זמין", "status_inactive": "לא זמין", "no_leads_found": "לא נמצאו לידים במערכת.",
        "status": "סטטוס נוכחי", "new": "חדש", "contacted": "בטיפול", "closed": "נסגר בהצלחה", "cancelled": "בוטל/לא רלוונטי", "booked": "נקבעה פגישה",
        "add_pro_title": "הוספת איש מקצוע חדש", "new_name": "שם העסק / איש המקצוע", "new_phone": "מספר טלפון (פורמט בינלאומי 972)",
        "new_type": "תחום עיסוק", "type_plumber": "אינסטלציה", "type_electrician": "חשמל",
        "new_areas": "ערים (מופרד בפסיקים)", "new_prices": "מחירון בסיס (טקסט חופשי)",
        "btn_create": "צור פרופיל ופתח יומן", "success_create": "הפרופיל נוצר בהצלחה! יומן עבודה הוגדר לשבוע הקרוב.",
        "title_schedule": "ניהול יומן ותורים",
        "sch_select_pro": "בחר יומן עבודה", "sch_date": "תאריך", "sch_time": "שעה", "sch_taken": "תפוס?",
        "sch_save": "שמור שינויים ביומן", "sch_success": "היומן עודכן בהצלחה!", "sch_filter_date": "סינון לפי תאריך",
        "sch_start_time": "שעת התחלה", "sch_end_time": "שעת סיום", "sch_delete": "מחיקה",
        "tab_daily": ":material/edit: עריכה יומית", "tab_bulk": ":material/settings: מחולל אוטומטי",
        "sch_config_title": "הגדרות יצירת יומן אוטומטי", "sch_start_date": "תאריך התחלה", "sch_end_date": "תאריך סיום",
        "sch_start_hour": "שעת התחלה יומית (0-23)", "sch_end_hour": "שעת סיום יומית (0-23)", "sch_duration": "משך פגישה (דקות)",
        "sch_workdays": "ימי עבודה פעילים", "sch_gen_btn": "צור יומן אוטומטי", "sch_clear_btn": "נקה סלוטים עתידיים",
        "sch_msg_generated": "הסלוטים נוצרו בהצלחה ביומן!", "sch_msg_cleared": "כל הסלוטים העתידיים נמחקו בהצלחה!",
        "day_0": "ראשון", "day_1": "שני", "day_2": "שלישי", "day_3": "רביעי", "day_4": "חמישי", "day_5": "שישי", "day_6": "שבת",
        "unknown_pro": "לא משויך", "select_lead": "בחר ליד לטיפול", "select_status": "עדכן סטטוס ל...",
        "no_slots": "אין תורים מוגדרים לתאריך זה.", "slot_help": "סמן בתיבה כדי לחסום את התור",
        "msg_changes": "שינויים נשמרו", "no_changes": "לא בוצעו שינויים לשמירה.",
        "schedule_empty": "היומן ריק כרגע. ניתן להשתמש ב'מחולל האוטומטי' כדי להגדיר שעות עבודה.",
        "disconnect": "🔒 יציאה מהמערכת",
        "btn_delete": "מחק ליד", "confirm_delete": "האם למחוק ליד זה לצמיתות?", "success_delete": "הליד נמחק בהצלחה", "edit_details": "עריכת פרטים", "edit_schedule": "שינוי מועד עבודה",
        "scheduler_title": "⏰ הגדרות תזמון אוטומטי", "sch_active": "פעיל?", "sch_run_time": "שעת ריצה יומית",
        "sch_run_now": "הפעל כעת 🚀", "sch_triggered": "הפקודה נשלחה לתזמון!", "sch_save_config": "שמור הגדרות תזמון"
    },
"EN": {
        "dir": "ltr", "align": "left",
        "nav_title": "Main Menu",
        "nav_dashboard": "📊 Dashboard", "nav_schedule": "📅 Schedule", "nav_add_pro": "➕ Add Professional", "nav_settings": "⚙️ System Settings", "nav_pros": "👷 Professionals",
        "welcome_message": "Welcome to Fixi Control Center", "admin_password_label": "Admin Password", "admin_password_placeholder": "Enter password...",
        "remember_me": "Keep me logged in", "login_button": "Login", "wrong_password": "❌ Invalid password.",
        "title_dashboard": "Control Center",
        "metric_total": "Total Leads", "metric_new": "Pending Leads", "metric_pros": "Active Staff",
        "table_title": "Lead Management",
        "col_date": "Date", "col_details": "Request Details", "col_status": "Status", "col_client": "Client Info", "col_pro": "Assigned To",
        "chat_history": "Conversation History", "no_chat": "No chat history available.",
        "action_update": "Lead Actions", "btn_update": "Update Status", "success_update": "Status updated successfully!",
        "settings_title": "System & AI Settings", "select_pro": "Select Profile", "edit_title": "Edit Profile", "save_btn": "Save Changes", "success_save": "Settings saved successfully!",
        "pros_title": "Professional Team", "phone": "Phone Number", "active": "Active Status", "areas": "Service Areas", "keywords": "Keywords", "prompt_title": "System Prompt", "prompt_desc": "Define bot personality and knowledge", "rating": "Client Rating", "role_user": "Client", "role_bot": "Digital Agent",
        "status_active": "Online", "status_inactive": "Offline", "no_leads_found": "No leads found.",
        "status": "Current Status", "new": "New", "contacted": "In Progress", "closed": "Completed", "cancelled": "Cancelled", "booked": "Booked",
        "add_pro_title": "Add New Professional", "new_name": "Business / Name", "new_phone": "Phone (Intl Format 972...)",
        "new_type": "Profession", "type_plumber": "Plumber", "type_electrician": "Electrician",
        "new_areas": "Cities (comma separated)", "new_prices": "Base Pricing (Free text)",
        "btn_create": "Create Profile & Schedule", "success_create": "Profile created! Initial schedule set for next week.",
        "title_schedule": "Schedule Management",
        "sch_select_pro": "Select Calendar", "sch_date": "Date", "sch_time": "Time", "sch_taken": "Taken?",
        "sch_save": "Save Schedule Changes", "sch_success": "Schedule updated!", "sch_filter_date": "Filter by Date",
        "sch_start_time": "Start Time", "sch_end_time": "End Time", "sch_delete": "Delete",
        "tab_daily": ":material/edit: Daily Editor", "tab_bulk": ":material/settings: Bulk Generator",
        "sch_config_title": "Auto-Schedule Generator", "sch_start_date": "Start Date", "sch_end_date": "End Date",
        "sch_start_hour": "Daily Start Hour", "sch_end_hour": "Daily End Hour", "sch_duration": "Meeting Duration (min)",
        "sch_workdays": "Active Workdays", "sch_gen_btn": "Generate Schedule", "sch_clear_btn": "Clear Future Slots",
        "sch_msg_generated": "Schedule generated successfully!", "sch_msg_cleared": "Future schedule cleared successfully!",
        "day_0": "Sunday", "day_1": "Monday", "day_2": "Tuesday", "day_3": "Wednesday", "day_4": "Thursday", "day_5": "Friday", "day_6": "Saturday",
        "unknown_pro": "Unassigned", "select_lead": "Select Lead", "select_status": "Change Status To",
        "no_slots": "No slots defined for this date.", "slot_help": "Check to block this slot",
        "msg_changes": "changes saved", "no_changes": "No changes to save.",
        "schedule_empty": "Schedule is empty. Use the Bulk Generator to create slots.",
        "disconnect": "🔒 Logout",
        "btn_delete": "Delete Lead", "confirm_delete": "Permanently delete this lead?", "success_delete": "Lead deleted successfully", "edit_details": "Edit Details", "edit_schedule": "Reschedule Job",
        "scheduler_title": "⏰ Auto-Scheduler Settings", "sch_active": "Active?", "sch_run_time": "Daily Run Time",
        "sch_run_now": "Run Now 🚀", "sch_triggered": "Command sent to scheduler!", "sch_save_config": "Save Configuration"
    }
}
