# מילון התרגומים המרכזי
TRANS = {
    "HE": {
        "dir": "rtl", "align": "right",
        "nav_title": "תפריט ראשי",
        "nav_dashboard": "📊 דשבורד ולידים",
        "nav_schedule": "📅 יומן עבודה",
        "nav_settings": "⚙️ הגדרות מערכת",
        "nav_professionals": "👷 אנשי מקצוע",
        "nav_analytics": "📊 אנליטיקס",

        "welcome_message": "ברוך הבא למרכז השליטה",
        "admin_username_label": "שם משתמש",
        "admin_password_label": "סיסמת מנהל",
        "admin_password_placeholder": "הכנס סיסמה כאן...",
        "remember_me": "זכור אותי (Keep me logged in)",
        "login_button": "כניסה למערכת",
        "wrong_password": "❌ סיסמה שגויה. נסה שוב.",

        "title_dashboard": "מרכז שליטה וניהול",
        "page_desc_dashboard": "צפה ונהל לידים נכנסים, עדכן את הסטטוס שלהם וסקור את היסטוריית השיחות.",
        "metric_total": 'סה"כ לידים',
        "metric_new": "לידים ממתינים",
        "metric_pros": "צוות פעיל",
        "table_title": "ניהול לידים ומשימות",
        "col_date": "תאריך פנייה",
        "col_details": "פרטי בקשה",
        "col_status": "סטטוס טיפול",
        "col_client": "פרטי לקוח",
        "col_pro": "משויך ל...",
        "chat_history": "היסטוריית התכתבות",
        "no_chat": "אין היסטוריה זמינה לשיחה זו.",
        "action_update": "פעולות על ליד נבחר",
        "btn_update": "עדכן סטטוס",
        "success_update": "הסטטוס עודכן בהצלחה!",
        "refresh_btn": "רענן לידים",
        "no_leads_found": "לא נמצאו לידים להצגה.",

        "pros_title": "צוות אנשי המקצוע",
        "page_desc_professionals": "נהל את רשימת אנשי המקצוע, הוסף חדשים, ערוך את פרטיהם והגדר את זמינותם.",
        "add_pro_title": "הוספת איש מקצוע חדש",
        "edit_pro_title": "עריכת איש מקצוע",
        "new_name": "שם העסק / איש המקצוע",
        "new_phone": "מספר טלפון (פורמט בינלאומי 972)",
        "new_type": "תחום עיסוק",
        "type_plumber": "אינסטלציה",
        "type_electrician": "חשמל",
        "type_handyman": "הנדימן",
        "type_locksmith": "מנעולן",
        "type_painter": "צבעי",
        "type_cleaner": "ניקיון",
        "type_general": "כללי",
        "new_areas": "ערים",
        "areas_help": "רשימת ערים מופרדת בפסיקים",
        "new_prices": "מחירון בסיס",
        "prices_help": "אופציונלי. פריט אחד בכל שורה, למשל: 'ביקור: 100 ש\"ח'",
        "btn_create": "צור פרופיל ופתח יומן",
        "success_create": "הפרופיל נוצר בהצלחה! יומן עבודה הוגדר לשבוע הקרוב.",
        "phone": "טלפון",
        "active": "פעיל במערכת?",
        "areas": "אזורי שירות (ערים)",
        "keywords": "מילות מפתח לזיהוי",
        "keywords_help": "מילות מפתח שיעזרו לבוט להבין את כוונת הלקוח",
        "prompt_title": "הנחיות אישיות לבוט (System Prompt)",
        "prompt_desc": "כאן מגדירים את האישיות והידע של הבוט עבור איש המקצוע",
        "prompt_help": "אזורי השירות יתווספו אוטומטית מהרשימה למעלה.",
        "rating": "דירוג לקוחות",
        "role_user": "לקוח",
        "role_bot": "נציג דיגיטלי",
        "status_active": "פעיל",
        "status_inactive": "לא פעיל",
        "action_add_new": "הוסף חדש",
        "action_view_all": "הצג הכל",
        "edit_btn": "ערוך",
        "delete_btn": "מחק",
        "confirm_delete_pro": "האם למחוק את איש המקצוע? פעולה זו אינה הפיכה.",
        "confirm_yes": "כן, מחק",
        "confirm_no": "לא",
        "cancel_btn": "בטל",
        "error_fill_fields": "אנא מלא את כל שדות החובה.",
        "back_to_list": "חזרה לרשימה",
        "ai_settings_title": "הגדרות AI",
        "tab_professionals": "אנשי מקצוע",
        "tab_pending_approval": "ממתינים לאישור",
        "no_pending_pros": "אין אנשי מקצוע הממתינים לאישור.",
        "approve_btn": "אשר",
        "reject_btn": "דחה",
        "confirm_reject_pro": "לדחות את איש המקצוע? הוא יקבל הודעה.",
        "registered_at": "נרשם בתאריך",

        "title_schedule": "ניהול יומן ותורים",
        "page_desc_schedule": "ערוך את לוח הזמנים היומי והשבועי של כל איש מקצוע.",
        "sch_select_pro": "בחר יומן עבודה",
        "sch_date": "תאריך",
        "sch_time": "שעה",
        "sch_taken": "תפוס?",
        "sch_save": "שמור שינויים ביומן",
        "sch_success": "היומן עודכן בהצלחה!",
        "sch_filter_date": "סינון לפי תאריך",
        "sch_start_time": "שעת התחלה",
        "sch_end_time": "שעת סיום",
        "sch_delete": "מחיקה",
        "tab_daily": ":material/edit: עריכה יומית",
        "tab_bulk": ":material/settings: מחולל אוטומטי",
        "sch_config_title": "הגדרות יצירת יומן אוטומטי",
        "sch_start_date": "תאריך התחלה",
        "sch_end_date": "תאריך סיום",
        "sch_start_hour": "שעת התחלה יומית (0-23)",
        "sch_end_hour": "שעת סיום יומית (0-23)",
        "sch_duration": "משך פגישה (דקות)",
        "sch_workdays": "ימי עבודה פעילים",
        "sch_gen_btn": "צור יומן אוטומטי",
        "sch_clear_btn": "נקה סלוטים עתידיים",
        "sch_msg_generated": "הסלוטים נוצרו בהצלחה ביומן!",
        "sch_msg_cleared": "כל הסלוטים העתידיים נמחקו בהצלחה!",
        "day_0": "ראשון", "day_1": "שני", "day_2": "שלישי", "day_3": "רביעי", "day_4": "חמישי", "day_5": "שישי", "day_6": "שבת",
        "no_slots": "אין תורים מוגדרים לתאריך זה.",
        "slot_help": "סמן בתיבה כדי לחסום את התור",
        "schedule_empty": "היומן ריק כרגע. ניתן להשתמש ב'מחולל האוטומטי' כדי להגדיר שעות עבודה.",
        "sch_msg_no_slots": "לא נוצרו סלוטים. בדוק את ההגדרות שלך.",
        "no_active_pros_for_schedule": "לא נמצאו אנשי מקצוע פעילים. אנא הוסף או הפעל איש מקצוע כדי לנהל את לוח הזמנים שלו.",

        "settings_title": "הגדרות מערכת ובוט AI",
        "page_desc_settings": "הגדר הגדרות מערכת גלובליות, כגון המתזמן האוטומטי.",
        "select_pro": "בחר פרופיל לעריכה",
        "edit_title": "עריכת פרופיל עסק",
        "save_btn": "שמור שינויים",
        "success_save": "השינויים נשמרו בהצלחה!",
        "scheduler_title": "⏰ הגדרות תזמון אוטומטי",
        "sch_active": "פעיל?",
        "sch_run_time": "שעת ריצה יומית",
        "sch_run_now": "הפעל כעת 🚀",
        "sch_triggered": "הפקודה נשלחה לתזמון!",
        "sch_save_config": "שמור הגדרות תזמון",
        "last_run": "ריצה אחרונה",
        "never": "מעולם לא",

        "status": "סטטוס נוכחי",
        "new": "חדש",
        "contacted": "בטיפול",
        "closed": "נסגר",
        "cancelled": "בוטל/לא רלוונטי",
        "booked": "נקבעה פגישה",
        "completed": "הושלם",

        "unknown_pro": "לא משויך",
        "select_lead": "בחר ליד לטיפול",
        "select_status": "עדכן סטטוס ל...",
        "disconnect": "🔒 יציאה מהמערכת",
        "btn_delete": "מחק ליד",
        "confirm_delete": "האם למחוק ליד זה לצמיתות?",
        "success_delete": "הליד נמחק בהצלחה",
        "edit_details": "עריכת פרטים",
        "edit_schedule": "שינוי מועד עבודה",
        "msg_changes": "שינויים נשמרו",
        "no_changes": "לא בוצעו שינויים לשמירה.",
        "select_lead_prompt": "בחר ליד מהרשימה כדי לראות פרטים.",
        "select_row_prompt": "בחר שורה בטבלה כדי לראות פעולות כמו היסטוריית צ'אט או מחיקה.",
        "confirm_clear_slots_title": "אישור מחיקה",
        "confirm_clear_slots_body": "האם למחוק את כל הסלוטים העתידיים שאינם תפוסים בטווח התאריכים שנבחר? פעולה זו אינה הפיכה.",

        "tab_dashboard": "📋 דשבורד",
        "tab_create_lead": "➕ יצירת ליד חדש",
        "create_lead_title": "יצירת ליד חדש",
        "create_lead_success": "הליד נוצר בהצלחה!",
        "input_client_name": "שם הלקוח",
        "input_client_phone": "מספר טלפון (וואטסאפ)",
        "input_issue": "תיאור התקלה",
        "input_status": "סטטוס התחלתי",
        "input_pro": "שיוך לאיש מקצוע",
        "submit_create_lead": "צור ליד",
        "error_phone_required": "מספר טלפון חובה."
    },
    "EN": {
        "dir": "ltr", "align": "left",
        "nav_title": "Main Menu",
        "nav_dashboard": "📊 Dashboard",
        "nav_schedule": "📅 Schedule",
        "nav_settings": "⚙️ System Settings",
        "nav_professionals": "👷 Professionals",
        "nav_analytics": "📊 Analytics",

        "welcome_message": "Welcome to Proli Control Center",
        "admin_username_label": "Username",
        "admin_password_label": "Admin Password",
        "admin_password_placeholder": "Enter password...",
        "remember_me": "Keep me logged in",
        "login_button": "Login",
        "wrong_password": "❌ Invalid password.",

        "title_dashboard": "Control Center",
        "page_desc_dashboard": "View and manage incoming leads, update their status, and review conversation history.",
        "metric_total": "Total Leads",
        "metric_new": "Pending Leads",
        "metric_pros": "Active Staff",
        "table_title": "Lead Management",
        "col_date": "Date",
        "col_details": "Request Details",
        "col_status": "Status",
        "col_client": "Client Info",
        "col_pro": "Assigned To",
        "chat_history": "Conversation History",
        "no_chat": "No chat history available.",
        "action_update": "Lead Actions",
        "btn_update": "Update Status",
        "success_update": "Status updated successfully!",
        "refresh_btn": "Refresh Leads",
        "no_leads_found": "No leads found to display.",

        "pros_title": "Professional Team",
        "page_desc_professionals": "Manage the list of professionals, add new ones, edit their details, and set their availability.",
        "add_pro_title": "Add New Professional",
        "edit_pro_title": "Edit Professional",
        "new_name": "Business / Name",
        "new_phone": "Phone (Intl Format 972...)",
        "new_type": "Profession",
        "type_plumber": "Plumber",
        "type_electrician": "Electrician",
        "type_handyman": "Handyman",
        "type_locksmith": "Locksmith",
        "type_painter": "Painter",
        "type_cleaner": "Cleaner",
        "type_general": "General",
        "new_areas": "Cities",
        "areas_help": "Comma-separated list of cities",
        "new_prices": "Base Pricing",
        "prices_help": "Optional. One item per line, e.g., 'Service call: $100'",
        "btn_create": "Create Profile & Schedule",
        "success_create": "Profile created! Initial schedule set for next week.",
        "phone": "Phone Number",
        "active": "Active Status",
        "areas": "Service Areas",
        "keywords": "Keywords",
        "keywords_help": "Keywords to help the bot understand customer intent",
        "prompt_title": "System Prompt",
        "prompt_desc": "Define bot personality and knowledge",
        "prompt_help": "Service areas will be added automatically from the list above.",
        "rating": "Client Rating",
        "role_user": "Client",
        "role_bot": "Digital Agent",
        "status_active": "Active",
        "status_inactive": "Inactive",
        "action_add_new": "Add New",
        "action_view_all": "View All",
        "edit_btn": "Edit",
        "delete_btn": "Delete",
        "confirm_delete_pro": "Are you sure you want to delete this professional? This is irreversible.",
        "confirm_yes": "Yes, Delete",
        "confirm_no": "No",
        "cancel_btn": "Cancel",
        "error_fill_fields": "Please fill in all required fields.",
        "back_to_list": "Back to list",
        "ai_settings_title": "AI Settings",
        "tab_professionals": "Professionals",
        "tab_pending_approval": "Pending Approval",
        "no_pending_pros": "No professionals pending approval.",
        "approve_btn": "Approve",
        "reject_btn": "Reject",
        "confirm_reject_pro": "Reject this professional? They will be notified.",
        "registered_at": "Registered",

        "title_schedule": "Schedule Management",
        "page_desc_schedule": "Edit the daily and weekly work schedule for each professional.",
        "sch_select_pro": "Select Calendar",
        "sch_date": "Date",
        "sch_time": "Time",
        "sch_taken": "Taken?",
        "sch_save": "Save Schedule Changes",
        "sch_success": "Schedule updated!",
        "sch_filter_date": "Filter by Date",
        "sch_start_time": "Start Time",
        "sch_end_time": "End Time",
        "sch_delete": "Delete",
        "tab_daily": ":material/edit: Daily Editor",
        "tab_bulk": ":material/settings: Bulk Generator",
        "sch_config_title": "Auto-Schedule Generator",
        "sch_start_date": "Start Date",
        "sch_end_date": "End Date",
        "sch_start_hour": "Daily Start Hour",
        "sch_end_hour": "Daily End Hour",
        "sch_duration": "Meeting Duration (min)",
        "sch_workdays": "Active Workdays",
        "sch_gen_btn": "Generate Schedule",
        "sch_clear_btn": "Clear Future Slots",
        "sch_msg_generated": "Schedule generated successfully!",
        "sch_msg_cleared": "Future schedule cleared successfully!",
        "day_0": "Sunday", "day_1": "Monday", "day_2": "Tuesday", "day_3": "Wednesday", "day_4": "Thursday", "day_5": "Friday", "day_6": "Saturday",
        "no_slots": "No slots defined for this date.",
        "slot_help": "Check to block this slot",
        "schedule_empty": "Schedule is empty. Use the Bulk Generator to create slots.",
        "sch_msg_no_slots": "No slots were generated. Check your settings.",
        "no_active_pros_for_schedule": "No active professionals found. Please add or activate a professional to manage their schedule.",

        "settings_title": "System & AI Settings",
        "page_desc_settings": "Configure system-wide settings, such as the auto-scheduler.",
        "select_pro": "Select Profile",
        "edit_title": "Edit Profile",
        "save_btn": "Save Changes",
        "success_save": "Settings saved successfully!",
        "scheduler_title": "⏰ Auto-Scheduler Settings",
        "sch_active": "Active?",
        "sch_run_time": "Daily Run Time",
        "sch_run_now": "Run Now 🚀",
        "sch_triggered": "Command sent to scheduler!",
        "sch_save_config": "Save Configuration",
        "last_run": "Last Run",
        "never": "Never",

        "status": "Current Status",
        "new": "New",
        "contacted": "In Progress",
        "closed": "Closed",
        "cancelled": "Cancelled",
        "booked": "Booked",
        "completed": "Completed",

        "unknown_pro": "Unassigned",
        "select_lead": "Select Lead",
        "select_status": "Change Status To",
        "disconnect": "🔒 Logout",
        "btn_delete": "Delete Lead",
        "confirm_delete": "Permanently delete this lead?",
        "success_delete": "Lead deleted successfully",
        "edit_details": "Edit Details",
        "edit_schedule": "Reschedule Job",
        "msg_changes": "changes saved",
        "no_changes": "No changes to save.",
        "select_lead_prompt": "Select a lead from the list to view details.",
        "select_row_prompt": "Select a row in the table to see actions like chat history or delete.",
        "confirm_clear_slots_title": "Confirm Deletion",
        "confirm_clear_slots_body": "Are you sure you want to delete all future non-booked slots within the selected date range? This action is irreversible.",
        "tab_dashboard": "📋 Dashboard",
        "tab_create_lead": "➕ Create New Lead",
        "create_lead_title": "Create a New Lead",
        "create_lead_success": "Lead created successfully!",
        "input_client_name": "Client Name",
        "input_client_phone": "Phone Number (Chat ID)",
        "input_issue": "Issue / Details",
        "input_status": "Initial Status",
        "input_pro": "Assign Professional",
        "submit_create_lead": "Create Lead",
        "error_phone_required": "Phone number is required."
    }
}
